<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '100071', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS ECONOMICAS Y ADMINISTRATIVAS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ADM', 'plan' => '9', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '100071', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS ECONOMICAS Y ADMINISTRATIVAS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CON', 'plan' => '9', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '100071', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS ECONOMICAS Y ADMINISTRATIVAS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ECO', 'plan' => '9', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '100071', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS ECONOMICAS Y ADMINISTRATIVAS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NEG', 'plan' => '3', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '100071', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS ECONOMICAS Y ADMINISTRATIVAS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIN', 'plan' => '3', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '150324', 'descripcion' => 'CIENCIAS NATURALES Y EDUCACION AMBIENTAL', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'INI', 'plan' => '7', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '150324', 'descripcion' => 'CIENCIAS NATURALES Y EDUCACION AMBIENTAL', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PRI', 'plan' => '7', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIL', 'plan' => '6', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIL', 'plan' => '6', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'FIL', 'plan' => '6', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'FIL', 'plan' => '6', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'FIL', 'plan' => '6', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '500002', 'descripcion' => 'INGLES BASICO I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'LEN', 'plan' => '7', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '150324', 'descripcion' => 'CIENCIAS NATURALES Y EDUCACION AMBIENTAL', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ESP', 'plan' => '7', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '210021', 'descripcion' => 'CASTELLANO I', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '500157', 'descripcion' => 'CONOCIMIENTO MATEMATICO Y ETNOMATEMATICO I', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '390295', 'descripcion' => 'CULTURA CIENTIFICO AMBIENTAL - BOTANICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '190040', 'descripcion' => 'HISTORIA UNIVERSAL I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '390277', 'descripcion' => 'LENGUA AMAZONICA I', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'BIL', 'plan' => '7', 'tc' => 'O', 'curso' => '390320', 'descripcion' => 'PRODUCCION AGRICOLA - CULTIVOS DE PAN LLEVAR', 'cred' => '2', 'ht' => '0', 'hp' => '4', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '150318', 'descripcion' => 'HISTORIA DE LOS ARCHIVOS', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ARC', 'plan' => '4', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '190003', 'descripcion' => 'HISTORIA DE LA CIVILIZACION', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '500002', 'descripcion' => 'INGLES BASICO I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TPC', 'plan' => '3', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '310003', 'descripcion' => 'BIOLOGIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '132103', 'descripcion' => 'CONCEPTOS MATEMATICOS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '360001', 'descripcion' => 'INTRODUCCION A LA ENFERMERIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ENF', 'plan' => '3', 'tc' => 'O', 'curso' => '310004', 'descripcion' => 'QUIMICA Y BIOQUIMICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '310003', 'descripcion' => 'BIOLOGIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '132103', 'descripcion' => 'CONCEPTOS MATEMATICOS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '260012', 'descripcion' => 'HISTORIA DE LA PSICOLOGIA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'PSI', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '310003', 'descripcion' => 'BIOLOGIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '132103', 'descripcion' => 'CONCEPTOS MATEMATICOS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'NUT', 'plan' => '3', 'tc' => 'O', 'curso' => '370008', 'descripcion' => 'QUIMICA ORGANICA E INORGANICA', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '310003', 'descripcion' => 'BIOLOGIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '132103', 'descripcion' => 'CONCEPTOS MATEMATICOS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '350011', 'descripcion' => 'INTRODUCCION A LA FISIOTERAPIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'TER', 'plan' => '3', 'tc' => 'O', 'curso' => '310004', 'descripcion' => 'QUIMICA Y BIOQUIMICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '200258', 'descripcion' => 'ESTRUCTURAS DISCRETAS I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '200257', 'descripcion' => 'FUNDAMENTOS DE SISTEMAS DE INFORMACION Y CIENCIAS DE LA COMPUTACION', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'O', 'curso' => '131042', 'descripcion' => 'MATEMATICA BASICA PARA INGENIERIA', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'ING', 'plan' => '6', 'tc' => 'E', 'curso' => '132095', 'descripcion' => 'HERRAMIENTAS DE OFIMATICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '132097', 'descripcion' => 'HERRAMIENTAS CAD', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '131002', 'descripcion' => 'INTRODUCCION A LA INGENIERIA INDUSTRIAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'O', 'curso' => '131042', 'descripcion' => 'MATEMATICA BASICA PARA INGENIERIA', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'IND', 'plan' => '6', 'tc' => 'E', 'curso' => '132095', 'descripcion' => 'HERRAMIENTAS DE OFIMATICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '132147', 'descripcion' => 'HERRAMIENTAS CAD PARA INGENIERIA CIVIL', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '132178', 'descripcion' => 'INTRODUCCION A LA INGENIERIA CIVIL', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'O', 'curso' => '131042', 'descripcion' => 'MATEMATICA BASICA PARA INGENIERIA', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'CIV', 'plan' => '6', 'tc' => 'E', 'curso' => '132095', 'descripcion' => 'HERRAMIENTAS DE OFIMATICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '200258', 'descripcion' => 'ESTRUCTURAS DISCRETAS I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '200257', 'descripcion' => 'FUNDAMENTOS DE SISTEMAS DE INFORMACION Y CIENCIAS DE LA COMPUTACION', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'O', 'curso' => '131042', 'descripcion' => 'MATEMATICA BASICA PARA INGENIERIA', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'SIS', 'plan' => '4', 'tc' => 'E', 'curso' => '132095', 'descripcion' => 'HERRAMIENTAS DE OFIMATICA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '261149', 'descripcion' => 'INTRODUCCION A LA INGENIERIA AMBIENTAL', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AMB', 'plan' => '3', 'tc' => 'O', 'curso' => '261146', 'descripcion' => 'QUIMICA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '261108', 'descripcion' => 'BIOLOGIA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '261244', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS AGRARIAS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGF', 'plan' => '3', 'tc' => 'O', 'curso' => '261146', 'descripcion' => 'QUIMICA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '261083', 'descripcion' => 'INTRODUCCION A LA INGENIERIA AGROINDUSTRIAL Y DE BIOCOMERCIO', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'BIO', 'plan' => '3', 'tc' => 'O', 'curso' => '261146', 'descripcion' => 'QUIMICA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '150286', 'descripcion' => 'ACTIVIDADES I', 'cred' => '1', 'ht' => '0', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '261108', 'descripcion' => 'BIOLOGIA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '261244', 'descripcion' => 'INTRODUCCION A LAS CIENCIAS AGRARIAS', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '132107', 'descripcion' => 'MATEMATICA 1', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'AGN', 'plan' => '2', 'tc' => 'O', 'curso' => '261146', 'descripcion' => 'QUIMICA GENERAL', 'cred' => '4', 'ht' => '2', 'hp' => '4', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '170001', 'descripcion' => 'ANTROPOLOGIA RELIGIOSA', 'cred' => '4', 'ht' => '4', 'hp' => '0', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '120082', 'descripcion' => 'INTRODUCCION A LA FILOSOFIA', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '120264', 'descripcion' => 'INTRODUCCION AL DERECHO I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '150283', 'descripcion' => 'LENGUA: COMUNICACION ESCRITA ACADEMICA', 'cred' => '5', 'ht' => '4', 'hp' => '2', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '240021', 'descripcion' => 'MATEMATICA BASICA I', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);
        Plan::create(['carrera' => 'DER', 'plan' => '4', 'tc' => 'O', 'curso' => '120232', 'descripcion' => 'TEORIA DE LOS VALORES', 'cred' => '3', 'ht' => '2', 'hp' => '2', ]);

    }
}
